# Generated by Django 5.1.7 on 2025-03-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exclude_flowers',
            field=models.ManyToManyField(to='flowers.flower'),
        ),
    ]
