# Generated by Django 5.1.7 on 2025-03-26 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_order_exclude_flowers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='BouquetOfFlowers',
        ),
        migrations.AddField(
            model_name='order',
            name='bouquet_of_flowers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='flowers.bouquetofflowers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bouquetofflowers',
            name='events',
            field=models.ManyToManyField(related_name='bouquets', to='flowers.event'),
        ),
        migrations.AlterField(
            model_name='bouquetofflowers',
            name='flowers',
            field=models.ManyToManyField(related_name='bouquets', to='flowers.flower'),
        ),
        migrations.AlterField(
            model_name='order',
            name='exclude_flowers',
            field=models.ManyToManyField(related_name='orders', to='flowers.flower'),
        ),
    ]
