# Generated by Django 5.1.7 on 2025-03-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_remove_order_bouquetofflowers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='exclude_flowers',
            field=models.ManyToManyField(blank=True, related_name='orders', to='flowers.flower'),
        ),
    ]
