# Generated by Django 5.1.7 on 2025-03-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0005_colorpalette_bouquetofflowers_color_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquetofflowers',
            name='byte_photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
