# Generated by Django 5.1.7 on 2025-03-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0006_bouquetofflowers_byte_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquetofflowers',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
