# Generated by Django 5.1.7 on 2025-03-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0007_alter_bouquetofflowers_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bouquetofflowers',
            old_name='byte_photo',
            new_name='binary_photo',
        ),
    ]
