# Generated by Django 5.1.7 on 2025-03-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0008_rename_byte_photo_bouquetofflowers_binary_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouquetofflowers',
            name='photo',
        ),
        migrations.AlterField(
            model_name='bouquetofflowers',
            name='binary_photo',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
